"""empty message

Revision ID: 2cdf7bea7a55
Revises: 1e9ebb90aff7
Create Date: 2023-12-29 16:38:24.332542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdf7bea7a55'
down_revision = '1e9ebb90aff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earning', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('earning')

    # ### end Alembic commands ###
