"""empty message

Revision ID: 3edada39ef15
Revises: 77bb35aecfa3
Create Date: 2023-12-24 14:44:30.677046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edada39ef15'
down_revision = '77bb35aecfa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('video_name', sa.String(length=250), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('video_name')
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
