"""empty message

Revision ID: 56f3b83a1a72
Revises: aae02f310491
Create Date: 2023-12-23 20:05:45.457942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f3b83a1a72'
down_revision = 'aae02f310491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_foreign_key('member_video_fk', 'members', ['creator'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint('member_video_fk', type_='foreignkey')

    # ### end Alembic commands ###
