"""empty message

Revision ID: aae02f310491
Revises: 4a3ff050612f
Create Date: 2023-12-21 13:24:00.170386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae02f310491'
down_revision = '4a3ff050612f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downlines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downline_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downlines', schema=None) as batch_op:
        batch_op.drop_column('downline_name')

    # ### end Alembic commands ###
