"""empty message

Revision ID: b4fa82fd6c2a
Revises: 2cdf7bea7a55
Create Date: 2023-12-30 11:03:48.368624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fa82fd6c2a'
down_revision = '2cdf7bea7a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yt_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('yt_id')

    # ### end Alembic commands ###
