"""empty message

Revision ID: f342fca57dd1
Revises: b4fa82fd6c2a
Create Date: 2023-12-30 23:17:53.139966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f342fca57dd1'
down_revision = 'b4fa82fd6c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stack', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_history', schema=None) as batch_op:
        batch_op.drop_column('stack')

    # ### end Alembic commands ###
